package dev.yuri.zzzplushies;

/** Agents whose first Obtain Agent audio is available on the ZZZ Wiki. */
public final class VoiceCatalog {
    private VoiceCatalog() {}
    public static final String[] IDS = {
        "alice_thymefield",
        "anby_demara",
        "anton_ivanov",
        "asaba_harumasa",
        "astra_yao",
        "banyue",
        "ben_bigger",
        "billy_kid",
        "burnice",
        "caesar_king",
        "corin_wickes",
        "dialyn",
        "ellen_joe",
        "evelyn_chevalier",
        "grace_howard",
        "hoshimi_miyabi",
        "hugo_vlad",
        "jane_doe",
        "ju_fufu",
        "koleda_belobog",
        "komano_manato",
        "lighter",
        "lucia",
        "lucy",
        "nekomiya_mana",
        "nicole_demara",
        "orphie_magus",
        "pan_yinhu",
        "piper_wheel",
        "pulchra_fellini",
        "qingyi",
        "rina",
        "seed",
        "seth_lowell",
        "soldier_0_anby",
        "soldier_11",
        "soukaku",
        "starlight_billy",
        "trigger",
        "tsukishiro_yanagi",
        "ukinami_yuzuha",
        "vivian_banshee",
        "von_lycaon",
        "ye_shunguang",
        "yidhari",
        "yixuan",
        "zhao",
        "zhu_yuan",
    };
}
