"""Generate the mod catalog and resources from the reviewed Minecraft skins.

Requires Pillow (`python -m pip install pillow`). Run from this project folder.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

from PIL import Image


PROJECT = Path(__file__).resolve().parent
SKINS = PROJECT.parent / "assets" / "zzz-plushie-skins"
RESOURCES = PROJECT / "src" / "main" / "resources"
NAMESPACE = "zzzplushies"
JAVA = PROJECT / "src" / "main" / "java" / "dev" / "yuri" / NAMESPACE


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def make_icon(skin: Image.Image, destination: Path) -> None:
    # Base face and optional headwear layer from the standard 64x64 player skin.
    face = skin.crop((8, 8, 16, 16)).convert("RGBA")
    hat = skin.crop((40, 8, 48, 16)).convert("RGBA")
    face.alpha_composite(hat)
    destination.parent.mkdir(parents=True, exist_ok=True)
    face.resize((16, 16), Image.Resampling.NEAREST).save(destination)


def main() -> None:
    source = (SKINS / "SOURCES.md").read_text(encoding="utf-8")
    entries: list[tuple[str, str, Path]] = []
    for line in source.splitlines():
        match = re.match(r"\| [^|]+ \| ([^|]+?) \| \[([^]]+\.png)\]", line)
        if not match:
            continue
        display = re.sub(r" \(lançamento em 30/09\)$", "", match.group(1).strip())
        filename = match.group(2)
        if filename.startswith(("belle__", "candidate_")):
            continue
        agent_id = filename.split("__", 1)[0]
        if not re.fullmatch(r"[a-z0-9_]+", agent_id):
            raise ValueError(f"Invalid registry name: {agent_id}")
        entries.append((agent_id, display, SKINS / filename))

    if len(entries) != 58 or len({entry[0] for entry in entries}) != 58:
        raise ValueError(f"Expected 58 distinct selected agents, found {len(entries)}")

    java = [
        "package dev.yuri.zzzplushies;",
        "",
        "/** Generated by generate_assets.py from the approved skin selection. */",
        "public final class PlushCatalog {",
        "    private PlushCatalog() {}",
        "    public static final String[] IDS = {",
    ]
    java += [f'        "{agent_id}",' for agent_id, _, _ in entries]
    java += ["    };", "}", ""]
    JAVA.mkdir(parents=True, exist_ok=True)
    (JAVA / "PlushCatalog.java").write_text("\n".join(java), encoding="utf-8")

    write_json(RESOURCES / "assets" / NAMESPACE / "models" / "block" / "empty.json",
               {"parent": "minecraft:block/block"})
    write_json(RESOURCES / "assets" / NAMESPACE / "models" / "item" / "plush_base.json",
               {"parent": "minecraft:item/generated", "textures": {"layer0": "minecraft:block/white_wool"}})
    write_json(RESOURCES / "data" / NAMESPACE / "recipes" / "plush_base.json", {
        "type": "minecraft:crafting_shaped",
        "pattern": [" S ", "SWS", " S "],
        "key": {"S": {"item": "minecraft:string"}, "W": {"item": "minecraft:white_wool"}},
        "result": {"item": f"{NAMESPACE}:plush_base", "count": 4},
    })

    en = {"itemGroup.zzzplushies.plushies": "ZZZ Plushies",
          "item.zzzplushies.plush_base": "Plush Base"}
    pt = {"itemGroup.zzzplushies.plushies": "Pelúcias de ZZZ",
          "item.zzzplushies.plush_base": "Base de pelúcia"}

    for agent_id, display, path in entries:
        with Image.open(path) as raw:
            if raw.format != "PNG" or raw.size != (64, 64):
                raise ValueError(f"Not a 64x64 Minecraft skin: {path}")
            skin = raw.convert("RGBA")
        target = RESOURCES / "assets" / NAMESPACE / "textures" / "entity" / f"{agent_id}.png"
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(path, target)
        make_icon(skin, RESOURCES / "assets" / NAMESPACE / "textures" / "item" / f"{agent_id}.png")
        write_json(RESOURCES / "assets" / NAMESPACE / "models" / "item" / f"{agent_id}.json", {
            "parent": "builtin/entity",
            "display": {
                "gui": {"rotation": [25, 20, 0], "translation": [0, 4, 0],
                        "scale": [0.9, 0.9, 0.9]},
                "ground": {"scale": [1, 1, 1]},
                "fixed": {"rotation": [0, 180, 0], "scale": [1, 1, 1]},
                "thirdperson_righthand": {"rotation": [75, 45, 0], "scale": [0.9, 0.9, 0.9]},
                "firstperson_righthand": {"rotation": [0, 45, 0], "scale": [0.9, 0.9, 0.9]},
            },
        })
        write_json(RESOURCES / "assets" / NAMESPACE / "blockstates" / f"{agent_id}.json", {
            "variants": {f"facing={direction}": {"model": f"{NAMESPACE}:block/empty"}
                         for direction in ("north", "east", "south", "west")},
        })
        write_json(RESOURCES / "data" / NAMESPACE / "loot_tables" / "blocks" / f"{agent_id}.json", {
            "type": "minecraft:block",
            "pools": [{"rolls": 1, "entries": [{"type": "minecraft:item", "name": f"{NAMESPACE}:{agent_id}"}],
                       "conditions": [{"condition": "minecraft:survives_explosion"}]}],
        })
        write_json(RESOURCES / "data" / NAMESPACE / "recipes" / f"{agent_id}.json", {
            "type": "minecraft:stonecutting",
            "ingredient": {"item": f"{NAMESPACE}:plush_base"},
            "result": f"{NAMESPACE}:{agent_id}",
            "count": 1,
        })
        en[f"block.{NAMESPACE}.{agent_id}"] = f"{display} Plush"
        pt[f"block.{NAMESPACE}.{agent_id}"] = f"Pelúcia de {display}"

    write_json(RESOURCES / "assets" / NAMESPACE / "lang" / "en_us.json", en)
    write_json(RESOURCES / "assets" / NAMESPACE / "lang" / "pt_br.json", pt)
    shutil.copyfile(SKINS / "SOURCES.md", PROJECT / "SKIN_SOURCES.md")
    print(f"Generated {len(entries)} plushes, textures, recipes, drops, icons and translations.")


if __name__ == "__main__":
    main()
